apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-argocd
  template:
    metadata:
      labels:
        app: gitops-argocd
    spec:
      containers:
      - name: gitops-argocd
        image: chmenegatti/gitops-argocd:latest
        ports:
        - containerPort: 5050
